services:
  - type: web
    name: currency-converter-backend
    env: java
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/*.jar"
    plan: free
    envVars:
      - key: JAVA_VERSION
        value: 21
